name: Releases

on:
  push:
    branches: ['main', 'next', 'dev']

jobs:
  release-latest:
    name: Release Latest
    if: github.ref == 'refs/heads/main' && "!contains(github.event.head_commit.message, '[skip releases]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Volta
        uses: volta-cli/action@fdf4cf319494429a105efaa71d0e5ec67f338c6e
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPM under latest tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          npx changeset version
          git add . 
          git commit -m "Publish to NPM as latest [skip releases]"
          npx changeset publish
          git push --follow-tags

  
  release-next:
    name: Release Next
    if: github.ref == 'refs/heads/next' && "!contains(github.event.head_commit.message, '[skip releases]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Volta
        uses: volta-cli/action@fdf4cf319494429a105efaa71d0e5ec67f338c6e
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPM under next tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          npx changeset pre enter next
          npx changeset version
          npx changeset publish
          npx changeset pre exit
          git add . 
          git commit -m "Publish to NPM under next tag [skip releases]"
          git push --follow-tags

  
  release-dev:
    name: Release Dev
    if: github.ref == 'refs/heads/dev' && "!contains(github.event.head_commit.message, '[skip releases]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Volta
        uses: volta-cli/action@fdf4cf319494429a105efaa71d0e5ec67f338c6e
        with:
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm install

      - name: Publish to NPM under dev tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          npx changeset pre enter dev
          npx changeset version
          npx changeset publish
          npx changeset pre exit
          git add . 
          git commit -m "Publish to NPM under dev tag [skip releases]"
          git push --follow-tags
